name: disquaire_django
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.3.0
  - backcall=0.2.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - colorama=0.4.4
  - console_shortcut=0.1.1
  - decorator=4.4.2
  - django=3.1.2
  - django-debug-toolbar=3.2.1
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - krb5=1.17.1
  - libpq=12.2
  - libsodium=1.0.18
  - openssl=1.1.1k
  - parso=0.8.0
  - pickleshare=0.7.5
  - pip=21.2.1
  - prompt-toolkit=3.0.8
  - psycopg2=2.8.5
  - pygments=2.7.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pywin32=227
  - pyzmq=19.0.2
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.36.0
  - sqlparse=0.4.1
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=5.0.5
  - ucrt=10.0.20348.0
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wcwidth=0.2.5
  - wheel=0.36.2
  - wincertstore=0.2
  - zeromq=4.3.2
  - zlib=1.2.11
